name: Create Pull Request for Environment Branches

on:
  push:
    branches:
      - feature*
      - fix*
    paths:
      - 'emilkle-oppg2/**'
  workflow_dispatch:

env: 
  GH_TOKEN: ${{ github.token }}
  REVIEWER: "emilkle"
  ASSIGNEE: "emilkle"

jobs:
  create_pull_request:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      - name: Check if 'dev' Branch Exists
        run: |
          git fetch origin main 
          if ! git ls-remote --exit-code --heads origin dev; then
            echo "Dev branch does not exist. Creating it now."
            git checkout main         
            git pull origin main       
            git checkout -b dev
            git push origin dev
          else
            echo "Dev branch exists."
          fi

      - name: Create Pull Request to Dev
        run: |
          gh pr create --base dev --head ${{ github.ref_name }} --title "Auto PR: Merge ${{ github.ref_name }} to dev" \
          --body "Automatic pull request created by GitHub Actions to merge changes from ${{ github.ref_name }} to dev." \
          --reviewer ${{ env.REVIEWER }} \
          --assignee ${{ env.ASSIGNEE }}
          
      - name: Remove Branch After Approval
        if: success()
        run: |
            gh pr merge --auto --squash --delete-branch ${{ github.ref_name }}
