name: Deploy Infrastructure to Production

on:
  pull_request:
    branches:
      - main
    paths:
      - 'emilkle-oppg2/**'
  workflow_dispatch:
    inputs:
      action_type:
        description: 'What terraform action do you want to perform? (apply/destroy)'
        required: true
        default: 'apply'
        type: choice
        options:
          - 'apply'
          - 'destroy'

env: 
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  GH_TOKEN: ${{ github.token }}
  WORKING_DIR: .
  REVIEWER: "emilkle"
  ASSIGNEE: "emilkle"

jobs:
  prod_stage:
    runs-on: ubuntu-22.04
    environment:
        name: production  
    steps:
      - name: Checkout  
        uses: actions/checkout@v4

      - name: Azure CLI Login
        run: |
          az login --service-principal -u ${{ env.ARM_CLIENT_ID }} -p ${{ env.ARM_CLIENT_SECRET }} --tenant ${{ env.ARM_TENANT_ID }}  
    
      - name: Terraform init, plan, and apply to prod workspace
        if: github.event.inputs.action_type == 'apply'
        run: |
          for dir in ${{ env.WORKING_DIR }}/*; do
            if { [ "$(basename "$dir")" == "application_plattform" ] || 
                                [ "$(basename "$dir")" == "core_infrastructure" ] || 
                                [ "$(basename "$dir")" == "global" ] ||
                                  [ "$(basename "$dir")" == "nn-deployment" ]; }; then
              cd "$dir"
              terraform workspace select prod || terraform workspace new prod
              terraform init
              terraform plan -var-file="${{ env.WORKING_DIR }}/$(basename "$dir")/terraform.tfvars.prod"
              terraform apply -auto-approve 
              cd ..
            fi
          done

    
      - name: Terraform destroy prod 
        if: github.event.inputs.action_type == 'destroy'
        run: |
          for dir in ${{ env.WORKING_DIR }}/*; do
            if { [ "$(basename "$dir")" == "application_plattform" ] || 
                                [ "$(basename "$dir")" == "core_infrastructure" ] || 
                                [ "$(basename "$dir")" == "global" ] ||
                                  [ "$(basename "$dir")" == "nn-deployment" ]; }; then
              cd "$dir"
              terraform init
              terraform workspace select prod || terraform workspace new prod
              terraform destroy -auto-approve
              cd ..
            fi  
          done
